1. а) умножение невозможно,
б) 2Х3, невозможно,
в) 8Х8, 3Х3,
г) 4Х4, 4Х4.

In [1]:
import numpy as np

In [3]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Сумма матриц A и B\n{a + b}')
print(f'Произведение матриц A и B\n{np.dot(a, b)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Сумма матриц A и B
[[ 5 -3]
 [ 3  5]]
Произведение матриц A и B
[[  4 -11]
 [ 12  -3]]


In [4]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица C\n{c}\n')
print(f'Матрица 3A - 2B + 4C\n{3*a - 2*b + 4*c}\n')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица C
[[ 2 -4]
 [ 1  1]]

Матрица 3A - 2B + 4C
[[ 11  -5]
 [  9 -12]]



In [12]:
a = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица A\n{a}\n')
print(f'Матрица AAt\n{np.dot(a, a.T)}\n')
print(f'Матрица AtA\n{np.dot(a.T, a)}\n')


Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица AAt
[[17 18 11]
 [18 29  4]
 [11  4 13]]

Матрица AtA
[[45  0]
 [ 0 14]]



In [19]:
def my_matrix_dot(matrix1, matrix2):
    s=0
    temp=[]
    result=[]
    if len(matrix2)!=len(matrix1[0]):
        print ("Матрицы не могут быть перемножены")        
    else:
        r1=len(matrix1) 
        c1=len(matrix1[0])    
        r2=c1           
        c2=len(matrix2[0])
        for z in range(0, r1):
            for j in range(0, c2):
                for i in range(0, c1):
                   s = s + matrix1[z][i] * matrix2[i][j]
                temp.append(s)
                s=0
            result.append(temp)
            temp=[]           
    return result

In [20]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Произведение матриц A и B\n{my_matrix_dot(a, b)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Произведение матриц A и B
[[4, -11], [12, -3]]


1.а) 1

In [21]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [22]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


2.а) 16

2.б) 4

2.в) 8

In [24]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


Определитель равен нулю, следовательно матрица вырожденная

In [25]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [26]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
